version: "3.9"

services:
  elasticsearch:
    # image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    image: elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - cluster.name=jetfork-es
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./data:/var/data/elasticsearch
      - ./logs:/var/log/elasticsearch