version: "3.9"

services:
  backend:
    build:
      context: ./src/backend
    ports:
      - "8000:8000"
    env_file: .env

  elasticsearch:
    image: elastic/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - cluster.name=jetfork-es
      # - bootstrap.memory_lock=true
      - discovery.type=single-node

      - xpack.security.enabled=false
      # - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
    env_file:
      - .env
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: elastic/kibana:8.11.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_NAME=https://jetfork.ru/kibana/
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  elasticsearch_data:
